apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-ag
  namespace: argocd
spec:
  destination:
    server: https://0F39B72AFCB1066EE43277992455A851.gr7.ap-south-1.eks.amazonaws.com
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/Satya4410/gitops-demo.git
    path: .
    targetRevision: HEAD