apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-app
spec:
  destination:
    namespace: default
    server: 'https://869A1B0B5F1FDC3F239AB16B12CF9402.gr7.ap-south-1.eks.amazonaws.com'  # URL of your Kubernetes API server
  project: default
  source:
    repoURL: 'https://github.com/Satya4410/gitops-demo.git'  # URL of your GitHub repository
    path: kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
